/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BancorConverterRegistryInterface extends ethers.utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "blockStamp()": FunctionFragment;
    "converterAddress(address,uint32)": FunctionFragment;
    "converterCount(address)": FunctionFragment;
    "newOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "registerConverter(address,address)": FunctionFragment;
    "tokenAddress(address)": FunctionFragment;
    "tokenCount()": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unregisterConverter(address,uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockStamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "converterAddress",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "converterCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "newOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerConverter",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterConverter",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blockStamp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "converterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "converterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerConverter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterConverter",
    data: BytesLike
  ): Result;

  events: {
    "ConverterAddition(address,address)": EventFragment;
    "ConverterRemoval(address,address)": EventFragment;
    "OwnerUpdate(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConverterAddition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConverterRemoval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdate"): EventFragment;
}

export class BancorConverterRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BancorConverterRegistryInterface;

  functions: {
    acceptOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "acceptOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    blockStamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    "blockStamp()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    converterAddress(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "converterAddress(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    converterCount(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "converterCount(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    newOwner(overrides?: CallOverrides): Promise<[string]>;

    "newOwner()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    registerConverter(
      _token: string,
      _converter: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerConverter(address,address)"(
      _token: string,
      _converter: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    tokenAddress(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "tokenAddress(address)"(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    tokenCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "tokenCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unregisterConverter(
      _token: string,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "unregisterConverter(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "acceptOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  blockStamp(overrides?: CallOverrides): Promise<BigNumber>;

  "blockStamp()"(overrides?: CallOverrides): Promise<BigNumber>;

  converterAddress(
    _token: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "converterAddress(address,uint32)"(
    _token: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  converterCount(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

  "converterCount(address)"(
    _token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  newOwner(overrides?: CallOverrides): Promise<string>;

  "newOwner()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  registerConverter(
    _token: string,
    _converter: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerConverter(address,address)"(
    _token: string,
    _converter: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  tokenAddress(_converter: string, overrides?: CallOverrides): Promise<string>;

  "tokenAddress(address)"(
    _converter: string,
    overrides?: CallOverrides
  ): Promise<string>;

  tokenCount(overrides?: CallOverrides): Promise<BigNumber>;

  "tokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "tokens(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    _newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unregisterConverter(
    _token: string,
    _index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "unregisterConverter(address,uint32)"(
    _token: string,
    _index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    "acceptOwnership()"(overrides?: CallOverrides): Promise<void>;

    blockStamp(overrides?: CallOverrides): Promise<BigNumber>;

    "blockStamp()"(overrides?: CallOverrides): Promise<BigNumber>;

    converterAddress(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "converterAddress(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    converterCount(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "converterCount(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newOwner(overrides?: CallOverrides): Promise<string>;

    "newOwner()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    registerConverter(
      _token: string,
      _converter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerConverter(address,address)"(
      _token: string,
      _converter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenAddress(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "tokenAddress(address)"(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<string>;

    tokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unregisterConverter(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "unregisterConverter(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ConverterAddition(_token: string | null, _address: null): EventFilter;

    ConverterRemoval(_token: string | null, _address: null): EventFilter;

    OwnerUpdate(
      _prevOwner: string | null,
      _newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    acceptOwnership(overrides?: Overrides): Promise<BigNumber>;

    "acceptOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    blockStamp(overrides?: CallOverrides): Promise<BigNumber>;

    "blockStamp()"(overrides?: CallOverrides): Promise<BigNumber>;

    converterAddress(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "converterAddress(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    converterCount(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "converterCount(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "newOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerConverter(
      _token: string,
      _converter: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerConverter(address,address)"(
      _token: string,
      _converter: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    tokenAddress(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenAddress(address)"(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    unregisterConverter(
      _token: string,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "unregisterConverter(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "acceptOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    blockStamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "blockStamp()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    converterAddress(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "converterAddress(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    converterCount(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "converterCount(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "newOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerConverter(
      _token: string,
      _converter: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerConverter(address,address)"(
      _token: string,
      _converter: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    tokenAddress(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenAddress(address)"(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unregisterConverter(
      _token: string,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "unregisterConverter(address,uint32)"(
      _token: string,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
