/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Multicall3Interface extends ethers.utils.Interface {
  functions: {
    "aggregate(tuple[])": FunctionFragment;
    "aggregate3(tuple[])": FunctionFragment;
    "aggregate3Value(tuple[])": FunctionFragment;
    "blockAndAggregate(tuple[])": FunctionFragment;
    "getBasefee()": FunctionFragment;
    "getBlockHash(uint256)": FunctionFragment;
    "getBlockNumber()": FunctionFragment;
    "getChainId()": FunctionFragment;
    "getCurrentBlockCoinbase()": FunctionFragment;
    "getCurrentBlockDifficulty()": FunctionFragment;
    "getCurrentBlockGasLimit()": FunctionFragment;
    "getCurrentBlockTimestamp()": FunctionFragment;
    "getEthBalance(address)": FunctionFragment;
    "getLastBlockHash()": FunctionFragment;
    "tryAggregate(bool,tuple[])": FunctionFragment;
    "tryBlockAndAggregate(bool,tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aggregate",
    values: [{ target: string; callData: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "aggregate3",
    values: [{ target: string; allowFailure: boolean; callData: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "aggregate3Value",
    values: [
      {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "blockAndAggregate",
    values: [{ target: string; callData: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getBasefee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentBlockCoinbase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentBlockDifficulty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentBlockGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentBlockTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEthBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastBlockHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tryAggregate",
    values: [boolean, { target: string; callData: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "tryBlockAndAggregate",
    values: [boolean, { target: string; callData: BytesLike }[]]
  ): string;

  decodeFunctionResult(functionFragment: "aggregate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "aggregate3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aggregate3Value",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockAndAggregate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBasefee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlockHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBlockCoinbase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBlockDifficulty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBlockGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBlockTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastBlockHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tryAggregate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tryBlockAndAggregate",
    data: BytesLike
  ): Result;

  events: {};
}

export class Multicall3 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Multicall3Interface;

  functions: {
    aggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "aggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    aggregate3(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "aggregate3(tuple[])"(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    aggregate3Value(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "aggregate3Value(tuple[])"(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    blockAndAggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "blockAndAggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    getBasefee(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { basefee: BigNumber }>;

    "getBasefee()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { basefee: BigNumber }>;

    getBlockHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { blockHash: string }>;

    "getBlockHash(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { blockHash: string }>;

    getBlockNumber(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { blockNumber: BigNumber }>;

    "getBlockNumber()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { blockNumber: BigNumber }>;

    getChainId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { chainid: BigNumber }>;

    "getChainId()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { chainid: BigNumber }>;

    getCurrentBlockCoinbase(
      overrides?: CallOverrides
    ): Promise<[string] & { coinbase: string }>;

    "getCurrentBlockCoinbase()"(
      overrides?: CallOverrides
    ): Promise<[string] & { coinbase: string }>;

    getCurrentBlockDifficulty(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { difficulty: BigNumber }>;

    "getCurrentBlockDifficulty()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { difficulty: BigNumber }>;

    getCurrentBlockGasLimit(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { gaslimit: BigNumber }>;

    "getCurrentBlockGasLimit()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { gaslimit: BigNumber }>;

    getCurrentBlockTimestamp(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { timestamp: BigNumber }>;

    "getCurrentBlockTimestamp()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { timestamp: BigNumber }>;

    getEthBalance(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    "getEthBalance(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    getLastBlockHash(
      overrides?: CallOverrides
    ): Promise<[string] & { blockHash: string }>;

    "getLastBlockHash()"(
      overrides?: CallOverrides
    ): Promise<[string] & { blockHash: string }>;

    tryAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "tryAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    tryBlockAndAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "tryBlockAndAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  aggregate(
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "aggregate(tuple[])"(
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  aggregate3(
    calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "aggregate3(tuple[])"(
    calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  aggregate3Value(
    calls: {
      target: string;
      allowFailure: boolean;
      value: BigNumberish;
      callData: BytesLike;
    }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "aggregate3Value(tuple[])"(
    calls: {
      target: string;
      allowFailure: boolean;
      value: BigNumberish;
      callData: BytesLike;
    }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  blockAndAggregate(
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "blockAndAggregate(tuple[])"(
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  getBasefee(overrides?: CallOverrides): Promise<BigNumber>;

  "getBasefee()"(overrides?: CallOverrides): Promise<BigNumber>;

  getBlockHash(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getBlockHash(uint256)"(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  "getBlockNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

  getChainId(overrides?: CallOverrides): Promise<BigNumber>;

  "getChainId()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentBlockCoinbase(overrides?: CallOverrides): Promise<string>;

  "getCurrentBlockCoinbase()"(overrides?: CallOverrides): Promise<string>;

  getCurrentBlockDifficulty(overrides?: CallOverrides): Promise<BigNumber>;

  "getCurrentBlockDifficulty()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentBlockGasLimit(overrides?: CallOverrides): Promise<BigNumber>;

  "getCurrentBlockGasLimit()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentBlockTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  "getCurrentBlockTimestamp()"(overrides?: CallOverrides): Promise<BigNumber>;

  getEthBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getEthBalance(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLastBlockHash(overrides?: CallOverrides): Promise<string>;

  "getLastBlockHash()"(overrides?: CallOverrides): Promise<string>;

  tryAggregate(
    requireSuccess: boolean,
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "tryAggregate(bool,tuple[])"(
    requireSuccess: boolean,
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  tryBlockAndAggregate(
    requireSuccess: boolean,
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "tryBlockAndAggregate(bool,tuple[])"(
    requireSuccess: boolean,
    calls: { target: string; callData: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    aggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string[]] & { blockNumber: BigNumber; returnData: string[] }
    >;

    "aggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string[]] & { blockNumber: BigNumber; returnData: string[] }
    >;

    aggregate3(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      ([boolean, string] & { success: boolean; returnData: string })[]
    >;

    "aggregate3(tuple[])"(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      ([boolean, string] & { success: boolean; returnData: string })[]
    >;

    aggregate3Value(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<
      ([boolean, string] & { success: boolean; returnData: string })[]
    >;

    "aggregate3Value(tuple[])"(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<
      ([boolean, string] & { success: boolean; returnData: string })[]
    >;

    blockAndAggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        ([boolean, string] & { success: boolean; returnData: string })[]
      ] & {
        blockNumber: BigNumber;
        blockHash: string;
        returnData: ([boolean, string] & {
          success: boolean;
          returnData: string;
        })[];
      }
    >;

    "blockAndAggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        ([boolean, string] & { success: boolean; returnData: string })[]
      ] & {
        blockNumber: BigNumber;
        blockHash: string;
        returnData: ([boolean, string] & {
          success: boolean;
          returnData: string;
        })[];
      }
    >;

    getBasefee(overrides?: CallOverrides): Promise<BigNumber>;

    "getBasefee()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBlockHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getBlockHash(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "getBlockNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    getChainId(overrides?: CallOverrides): Promise<BigNumber>;

    "getChainId()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentBlockCoinbase(overrides?: CallOverrides): Promise<string>;

    "getCurrentBlockCoinbase()"(overrides?: CallOverrides): Promise<string>;

    getCurrentBlockDifficulty(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockDifficulty()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentBlockGasLimit(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockGasLimit()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentBlockTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockTimestamp()"(overrides?: CallOverrides): Promise<BigNumber>;

    getEthBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getEthBalance(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastBlockHash(overrides?: CallOverrides): Promise<string>;

    "getLastBlockHash()"(overrides?: CallOverrides): Promise<string>;

    tryAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      ([boolean, string] & { success: boolean; returnData: string })[]
    >;

    "tryAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      ([boolean, string] & { success: boolean; returnData: string })[]
    >;

    tryBlockAndAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        ([boolean, string] & { success: boolean; returnData: string })[]
      ] & {
        blockNumber: BigNumber;
        blockHash: string;
        returnData: ([boolean, string] & {
          success: boolean;
          returnData: string;
        })[];
      }
    >;

    "tryBlockAndAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        ([boolean, string] & { success: boolean; returnData: string })[]
      ] & {
        blockNumber: BigNumber;
        blockHash: string;
        returnData: ([boolean, string] & {
          success: boolean;
          returnData: string;
        })[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    aggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "aggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    aggregate3(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "aggregate3(tuple[])"(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    aggregate3Value(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "aggregate3Value(tuple[])"(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    blockAndAggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "blockAndAggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    getBasefee(overrides?: CallOverrides): Promise<BigNumber>;

    "getBasefee()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBlockHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBlockHash(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "getBlockNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    getChainId(overrides?: CallOverrides): Promise<BigNumber>;

    "getChainId()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentBlockCoinbase(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockCoinbase()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentBlockDifficulty(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockDifficulty()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentBlockGasLimit(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockGasLimit()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentBlockTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentBlockTimestamp()"(overrides?: CallOverrides): Promise<BigNumber>;

    getEthBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getEthBalance(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastBlockHash(overrides?: CallOverrides): Promise<BigNumber>;

    "getLastBlockHash()"(overrides?: CallOverrides): Promise<BigNumber>;

    tryAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "tryAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    tryBlockAndAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "tryBlockAndAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "aggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    aggregate3(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "aggregate3(tuple[])"(
      calls: { target: string; allowFailure: boolean; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    aggregate3Value(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "aggregate3Value(tuple[])"(
      calls: {
        target: string;
        allowFailure: boolean;
        value: BigNumberish;
        callData: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    blockAndAggregate(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "blockAndAggregate(tuple[])"(
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    getBasefee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBasefee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBlockHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBlockHash(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBlockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBlockNumber()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getChainId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentBlockCoinbase(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCurrentBlockCoinbase()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentBlockDifficulty(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCurrentBlockDifficulty()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentBlockGasLimit(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCurrentBlockGasLimit()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentBlockTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCurrentBlockTimestamp()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEthBalance(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEthBalance(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastBlockHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getLastBlockHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tryAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "tryAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    tryBlockAndAggregate(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "tryBlockAndAggregate(bool,tuple[])"(
      requireSuccess: boolean,
      calls: { target: string; callData: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
